eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override.system-properties: false
management:
  tracing:
    sampling:
      probability: 1.0
security:
  jwt:
    token:
      secret-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCp/o2Svzyb8OCpk9bNos82oFWAD1KnEuZndZptVNUnrv4XKNW6/QUcXyWmkqPvls4w5qxAxUNqzjiEOcL1A/uCHDzs1mUkRnmRN2j/p1AXQsWghS58vEXlkruSrzy7W5hASzKGEkqHF3GOUG/GkhkQhpW12JuRvCmMj7zwwHJil1gQQEyNrdPlzweoCCpS91HSN1UNWNMynaYaX9/svyDj2kewAYYxa0StK6+EIIXtGXyZDVRRQYjMF035rLIlfX0qT6VhVtwdV3sw0Y1KDWKOHJDV92EVGlm1A77vuacppwAugiXu9lS1NtmiryKia8Y2hWdRCEUsk2GYAEWUSxuHAgMBAAECggEAT66trtUsNE5nCKXvQImpxonGOhY0oHLoBCPohIoItia9HJ77/D/ApwlkbR18cYBHWz2tDVlJ3iUW8cfffhjlShoxZrSiSSwtrKeD9J35GUYnu7Ph0/8uZktu1/WDKrFm/vAgmR62x3byOAq1MidmT0w+nbQQS/Ieqa/wmQskMtjIp6fXO7Ei3DGaPBfZVsHdtyQK15NthgOk7Hx6l/0bcjXSdGVKfVbA81//3baiRbY+d1+Y1X6nPiBXswgRR5RmbJ9wFhRfzuWq0ZQGdqM2NJLhhn5TRM14/Mx2eRoPU2fEFVZz5U0n5qwHW3p27K05kLEZ+DNexa0aI8phQQjwIQKBgQDlw3rHV3em9aITcvonpgTha5TreqBcFqWRUby3y1I/irEwlHELUWfjBoQXebz6AG5A+7A2Ip66W/7TvYiAdMCYQGGmDhPVtwznTTgPLRW4KKc6KB8zJOzTpoQ2oc6tQHCrAqLFpMQc8DvGVtxgA6zvu5T91c4FpCbAK+ZXdmTcoQKBgQC9Z+FgO1I1eiyKwhCNf26ctbzb2mlBO95Bm77pJG6Y9gxfK2ZsAt/OwG9GOZgCktNbZth9L+cbBBW2VCCGWD5GgtIg5X9zsNWbeYHqud9pkE//6XvyU+xbkPE/qkcGLqvCfBtd6JPVnGfbJ064rVYL7XkRLFkx2mbXH8EJYnYfJwKBgFonOJ7NGDrfuMeu3q79+n5EyzsWc6OOk0qQ6t6nHc+m6N2p8S1CtOOko+HeN6NU1e4Tk9G6BdQT0spcXRoiNYvH/0i7z1aVK6/6YZu60gHfmbY9FfjobTCi7s/M756VYWAIebvZacX9EUdCv9fAuXObg9uRr/QQs8/Fqez5nJvhAoGAVMzTrSAiGGtQ0fc9Lfzl6ye7HLvW8Cv7wGgYu41iLv3KYDmwK5/F0G175HcYxd4y3vNW7gWqdQAJMI7N2RhdGXis16movIVpvahTMGJz0nGYP72rjr1gT0a/nH+CORRgNj0Wi577wWG7ZfVdW3XP1ptF3xh5/sYH0T0YUjlRJXUCgYEAyg4kbS0JmA/hOM0nLMwUpVxYbGNwjXXxVeuLuMFDBVEOmHJgow2hLm9WxLWvYvfW/SbC/w1MRQq1Yo6HqH/dNjJfQxgUvr0ShsO0v1eMmpmXWahKfagyN+9yyw5ktIyfls/BtCmDY5NvkgqDpwu/uYWIzulMz33FoGoHlDplnUE="
      accessExpiration: 3600000
      refreshToken: 36000000
      public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvuSTrqc8tEV/XTf3ngnVnKA7KvPPyrJuPinPHUq6h3BB7Ol4dA4yAv9jfrThy+S9QfuCRET/mEjROo1dhRQZw+c+GQUO1Ndz+v6Z43KRCnlNOuyWVqSQzmVHH8iTUEYfsP/1BNU55x4MweRp/cdDyHDvt8VmteS40Zawq0PtUzcXeh0Wi0X4nU5UkxQ/EF1XwAFEmnVMsRtsWeL888eC1lh3buGIAakibHmzcL8U8JqhSDQ1xKw9XENwIY+ZSt691ay3I2qkfBuzNf+0M00S6a0ALHGpOdzIpHUilLP+0dE+MnouhcyTCk65cB2RwwP6Nd6VHXI94LLqKaCxurprJQIDAQAB"
