spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content
    username: root
    driver-class-name: org.postgresql.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enable: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8060