spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/jwt/**,/api/v1/users/**,/api/v1/auth/**
server:
  port: 8222