spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: root
    driver-class-name: org.postgresql.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enable: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: createUserMessage:io.github.marianciuc.streamingservice.user.kafka.messages.CreateUserMessage
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: users-service-group
      properties:
        spring.json.trusted.packages: "io.github.marianciuc.streamingservice.users.dto"
server:
  port: 8050
jwt:
  private-key: '{"p":"1ZohVplIXHLokrHTX_9bgklOJw41aSqd5ruLRnKbcf4eT0T8FNQKzWYKRp-BglEF5OTyb_AF2bS14h8tPm0Xy2RnhhoLWcQtDhrEvuU454klX05cZUzNuEP-kKDIH75ykNLt_UhrTZqISXJhvk2miuwxaJUhSP3Ebn9cszoVEH8","kty":"RSA","q":"5AXbfuqJVcLtcW6L64SgMgyGRnMxJYxpMQaKtoUIzCB70dWH-pxAW70Erssg3i7H48MbkzwigFRdqwMdop1lAsQeKrCp4lp5lUsqp3m9EVzuyHBn7LFDi23iQVdwgs4aO4AvoDplvyYRU87DJ7WLNoNcBu896n3iD_ebWjMOQcs","d":"Tt89cJoQjbJvx1winWTQ1AFe4ymCyZlVtSS0scTjjs183eaY0oFHEePdsH_gPCpL9vCxNtr00q1pXh_OrTscs0FWIAZJMKmm9K7rwTAAZJ5H13LdeOpviHB2AA8W9uwR-SotXjm3eDydAO6wk4l3o65GGZp8yYbE6-eeIwYgLMvd7z-9jCJo-QBl-4nmn-UPjKuL9uqAj2Q8P9RW8N7PPVySpZsGhhkqvDp3m8e_OKXlxKDNk0LOKuOYyO9ko8BXg2aKCc5m4HKM42EiWJHF5Ar8i-5Vc5CvJWQCAA4NHUYKMwK2o0qtf0h8_pFYzUEUEjEQJ-B1RPVH1D6WJhlmNw","e":"AQAB","kid":"Outl4hhj-Ne-2J1OeK6x2CZUM1RNayGFef677upqJRw","qi":"1F991nyNpz5HyTTYVoeTVp5ngjNumuWd-6UW8BMew0QR7xfjVTiLE4BSEIgkUQ-bD200yzF5clP_pVegymD6lq4UBXSKOVOGWEsKmilLIA55rAPh0grp7_A7wTypOwXDiB_ORt9s3EU9Q2E66YXuUie9F7Z9jcP3_tb2o7bPH2g","dp":"iPASFXGZeWNVhM4qI-4SnXkfeFxck3p11nk_db99tlvi1JD2RugVsM6NIe-aWJBXBgJdBrRLG-IFhNzV5aKM0aEh2VATHM5u0A8LORK9I3rCEdKr22mcrVgx-EiLZAZ1bjE7z9hAqnS6kNOapCUl8wQvPMv2ldPSvcA7Ds_at0M","dq":"BL_Oe409AQlHUsZ_qY8gmwpBvbPmgSa0hi3hs71_mmjOy2cMJv8cJA0CzPU0IQyOY0MMDvwAp_WZ4db1xg5LLUySaEc3spw5zg87uzNA6dyqqIgW0go7IutN_BhrIn5Sc4zO8SJmPh333GwBCpGwbZk80HQpMPogPD7nAHDxyhM","n":"vkIo2IdIaARPhoWkPziGJiKsqB-HHhVCrLZO9QORzu1YPgiqj5MDaGqyzHo4EyIPOrIBV9qbl9zfaESuFZXaV00rrDx8drIreE_yNMr_ihdJqyyezsefpuYr_9c1nq7Tzh4l7hkDq3ER1moyx-vdiuwjv5xn7qh45jhNBun8XLUaIN4xvPoH6dYQJjHBuJscryX0OwW3N6LKLCTHk2L7c3TKwrPtwPVN7UL1-_atTDrdWVHL3KqzGup-XnGfAOUiu9sPOXTyFZcggwcjQoUEfdp00mhGFMvUqdZfxts3Jc-wgTOAN0hd_775HKmpq6znVOM33b4JedZD1RT0m9ZTtQ"}'
  public-key: '{"kty":"RSA","e":"AQAB","kid":"Outl4hhj-Ne-2J1OeK6x2CZUM1RNayGFef677upqJRw","n":"vkIo2IdIaARPhoWkPziGJiKsqB-HHhVCrLZO9QORzu1YPgiqj5MDaGqyzHo4EyIPOrIBV9qbl9zfaESuFZXaV00rrDx8drIreE_yNMr_ihdJqyyezsefpuYr_9c1nq7Tzh4l7hkDq3ER1moyx-vdiuwjv5xn7qh45jhNBun8XLUaIN4xvPoH6dYQJjHBuJscryX0OwW3N6LKLCTHk2L7c3TKwrPtwPVN7UL1-_atTDrdWVHL3KqzGup-XnGfAOUiu9sPOXTyFZcggwcjQoUEfdp00mhGFMvUqdZfxts3Jc-wgTOAN0hd_775HKmpq6znVOM33b4JedZD1RT0m9ZTtQ"}'