spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
application:
  config:
    security-server-url: http://localhost:8222/api/v1/auth
server:
  port: 8030