services:
  # PostgresSQL service
  postgres:
    container_name: ms_pg_sql_streaming_service
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - streaming-service-app-net
    restart: unless-stopped

  # Zipkin service
  zipkin:
    container_name: zipkin_streaming_service
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - streaming-service-app-net

  # Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_streaming_service
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - streaming-service-app-net

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka_streaming_service
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - streaming-service-app-net

  # Mail Dev service
  mail-dev:
    container_name: ms_mail_streaming_service_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  
  # MinIO service
  minio:
    container_name: ms_minio_streaming_service
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - streaming-service-app-net

  # MongoDb service
  mongodb:
    container_name: ms_mongodb_streaming_service
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

networks:
  streaming-service-app-net:
    driver: bridge

volumes:
  postgres:
  mongo:
