spring:
  application:
    name: media-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: localhost
      port: 6379
      password: root
  datasource:
    url: jdbc:postgresql://localhost:5432/media_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    oracleucp:
      database-name: media_db
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        default_schema: public
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
    default-schema: public
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: media-service-group
      properties:
        spring.json.trusted.packages: "io.github.marianciuc.streamingservice.media.dto"
mime:
  url: http://localhost:9000
  access-key: root
  secret-key: root
  bucket-name: media-bucket
server:
  port: 8054
logging:
  level:
    org.flywaydb: DEBUG
